### ISSUE TITLE
Revisar Política de Privacidade para possibilitar coleta de dados demográficos via Google Analytics

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/terms-policy#1]

**Comment by renatomurasaki** [comment]
@viniciusandrade as seguintes alterações na Política de Privacidade precisam ser feitas para implementar o botão de aceitaçao de cookies nos sites e iniciar a coleta de dados demográficos dos usuários:

### Alteração 1

**DE:**
Uso dos sites

Em geral você pode consultar os sites da BIREME/OPAS sem dizer quem é nem revelar nenhum tipo de informação pessoal. A única informação que compilamos durante uma consulta geral provém dos registros ordinários do servidor e inclui seu endereço IP (protocolo da internet), o nome do domínio, o tipo de navegador, o sistema operacional e informação sobre como chegou a nós, os arquivos que baixou, os sites que consultou e a data e hora dessas consultas.

**PARA:**
Uso dos sites

Em geral você pode consultar os sites da BIREME/OPAS sem dizer quem é. A informação compilada durante uma consulta geral provém dos registros ordinários do servidor e inclui seu endereço IP (protocolo da internet), o nome do domínio, o tipo de navegador, o sistema operacional e informação sobre como chegou a nós, os arquivos que baixou, os sites que consultou e a data e hora dessas consultas. Dados demográficos também podem ser coletados durante uma consulta, caso você esteja autenticado em um serviço de terceiros com permissão de compartilhar sua informação de idade, gênero e categorias de interesse.

### Alteração 2
**DE:**
O que a BIREME/OPAS faz com a informação que compila?

A informação compilada durante uma consulta geral é usada para analisar tendências e o uso dos sites da BIREME/OPAS, bem como para melhorar a utilidade desses sites. Não está conectada a nenhum tipo de dados pessoais.

**PARA:**
O que a BIREME/OPAS faz com a informação que compila?

A informação compilada durante uma consulta geral é usada para analisar tendências e o uso dos sites da BIREME/OPAS, bem como para melhorar a utilidade desses sites. 

### Alteração 3
**DE:**
SEGURANÇA

Não vendemos nem trocamos nenhum tipo de informação pessoal proporcionada voluntariamente nos sites da BIREME/OPAS a terceiros. Toda a informação fornecida à BIREME/OPAS pelos usuários dos sites da BIREME/OPAS é guardada com grande cuidado e segurança, e não se usará de maneira diferente das estabelecidas por essa política de privacidade, em qualquer política própria do site, ou das que você autorizou explicitamente.

**PARA:**
SEGURANÇA

Toda a informação fornecida à BIREME/OPAS pelos usuários dos sites da BIREME/OPAS é guardada com grande cuidado e segurança, e não se usará de maneira diferente das estabelecidas por essa política de privacidade, em qualquer política própria do site, ou das que você autorizou explicitamente.

**Comment by viniciusandrade** [comment]
Texto atualizado para os 3 idiomas.
